### PR TITLE
Added load file button + with drag and drop and added a favicon

### PR DESCRIPTION
**Pull request by BenKaufman10**
Added a button to load a file and added the option to load a file to the editor using drag and drop.
Added a new favicon to make the tab easier to identify and also to make it look better.
(hope this time everything is good with git).

### CODE REVIEW

**Comment by holgerd77** [comment]
Hi Ben, can you make sure, that the input field with the file name is vertically aligned with buttons on desktop width, now it is hanging somewhere in between:

bildschirmfoto 2018-03-29 um 12 21 00

On mobile width this should switch to the input field filling the whole row and the buttons filling the next (see [Bootstrap Grid options](https://getbootstrap.com/docs/4.0/layout/grid/#grid-options)).

bildschirmfoto 2018-03-29 um 12 21 12

**Comment by holgerd77** [comment]
The name displayed in the input field should reset to the ``my_file`` name when first loading a file and then opening an example.

**Comment by holgerd77** [comment]
And please put the new JS functions in the ``api-x.x.js`` file and not directly in the ``index.html``. Otherwise this looks good, really nice feature!

**Comment by holgerd77** [comment]
Favicon is particularly cool, just discovered! 😄

**Comment by BenKaufman10** [comment]
Thanks,
I will fix the filename design and move the js.
When you say the name should reset you mean when the user loads one of the example files right?

**Comment by holgerd77** [comment]
Yes, that should be an easy fix in ``API.loadExample()``.

**Comment by BenKaufman10** [comment]
I committed the new fixes into here.

**Comment by holgerd77** [comment]
Hmm, the layout options from my first comment are not really fixed, this would have to be done with the Bootstrap CSS grid classes I mentioned in the comment.

Anyway, I will treat this as a separate issue and merge this, then you can continue.

Before the next PR update your fork master branch (google: "Update GitHub fork") with latest changes from here and then start a new branch.

**Comment by holgerd77** [comment]
Ok, deployed this on https://vyper.online. 😄 Thanks again for the contribution!

**Comment by BenKaufman10** [comment]
Sure, thanks for the help. I will check out the Bootstrap issue.

**Pull request merged**
