### PR TITLE
Added new Vyper Highlighter and Desktop Version Using Electron

### PR DESCRIPTION
**Pull request by BenKaufman10**
Added a Load file button, and drag and drop capability to load a file.
Replaced the Python Highlighter with a custom Vyper Highlighter.
Added Node.js and Electron.js to create a desktop version.
Added download link for Desktop versions for all platforms.
UI improvements and a new favicon.

### CODE REVIEW

**Comment by holgerd77** [comment]
Hi Ben, you have to be a bit more careful on what you are committing and pre-check your commit with ``git status``, you have added all the ``node_modules`` within this commit.

**Comment by BenKaufman10** [comment]
Sorry for that, I removed the node modules directory.
I still don't know why GitHub gives me conflicts as I did pulled the newest version before (might didn't pulled correctly?)

**Comment by holgerd77** [comment]
Yes, actually I have to stop you a bit.

Something like this (adding all the node_modules) can't be reverted by another commit. This will still be in the commit history and gives to much bloat to the repository.

Generally: Please separate all functionality which is distinct/not overlapping into separate pull requests. This will otherwise get far too difficult to review and also mixes up discussion on features.

The Favicon is the only thing I would accept here as an addition to an existing PR, cause it's such a tiny change.

All other things should be handled separately:
- Load Button + File load
- Vyper Highlighter
- Electron support

**Comment by holgerd77** [comment]
This will also make things like resolving conflicts GitHub is showing far easier.

**Comment by holgerd77** [comment]
You can actually see this when you go to the GitHub page of your fork and switch to your ``beta`` branch that the fork branch is behind the latest commits from the original repository:
https://github.com/BenKaufman10/editor/tree/beta

**Comment by BenKaufman10** [comment]
Alright, sorry, I am still not used to GitHub. I'll try my best with it and still want to contribute to the project but I will probably still have mistakes using Git.
So for now you want me to separate each feature to its own branch, push 3 new PRs (one for each feature/ branch) and remove the last 2 commits with the nodes_module folder.
I let me check how I do it, if you have any resource explaining that it can be good.
For now should I close this PR?

**Comment by holgerd77** [comment]
I know this is a bit annoying and one is probably saying "URgh" on such a comment on first sight.

But I would advise you for this time to start a bit from scratch. Back up your local repository, delete your fork on GitHub and fork again. Then clone the repository again, do a new feature branch, e.g. ``vyper-highlighter`` and manually re-add the changes there. Then push your branch and submit a PR. I will try to review quickly.

After that make sure that you update your master branch with the changes merged and start a new branch with the next feature.

**Comment by BenKaufman10** [comment]
Will do so, thanks.

**Pull request closed without merging**
